title: George Sánchez
# logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: Operating at the intersection of Financial Economics, AI Engineering, and Data Science
theme: jekyll-theme-minimal
